In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import sys
print(sys.executable)

/Users/TURJOY/Documents/spam_detector/.venv/bin/python

In [4]:
print("hello z")

hello z

In [5]:
df = pd.read_csv("/Users/TURJOY/Documents/spam_detector/spam_ham_dataset.csv")
#print(data)
print("data info")
df.info()
print(df.isnull().sum())
df.head

data info
<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5171 non-null   int64
 1   label       5171 non-null   str
 2   text        5171 non-null   str
 3   label_num   5171 non-null   int64
dtypes: int64(2), str(2)
memory usage: 161.7 KB
Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

<bound method NDFrame.head of       Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3           4685  spam  Subject: photoshop , windows , office . cheap ...
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...
...          ...   ...                                                ...
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...
5169        1409   ham  Subject: industrial worksheets for august 2000...
5170        4807  spam  Subject: important online banking alert\r\ndea...

      label_num
0             0
1             0
2             0
3             1
4             0
...         ...
5166          0
5167          0
5168          0
5169          0
5170          1

[5171 rows x 4 columns]>

In [6]:
df.describe()

        Unnamed: 0    label_num
count  5171.000000  5171.000000
mean   2585.000000     0.289886
std    1492.883452     0.453753
min       0.000000     0.000000
25%    1292.500000     0.000000
50%    2585.000000     0.000000
75%    3877.500000     1.000000
max    5170.000000     1.000000

In [7]:
df.nunique().sort_values()

label            2
label_num        2
text          4993
Unnamed: 0    5171
dtype: int64

In [8]:
df["text"].value_counts()

text
Subject: calpine daily gas nomination\r\n>\r\nricky a . archer\r\nfuel supply\r\n700 louisiana , suite 2700\r\nhouston , texas 77002\r\n713 - 830 - 8659 direct\r\n713 - 830 - 8722 fax\r\n- calpine daily gas nomination 1 . doc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     20
Subject: \r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         16
Subject: \r\nthis week only : f . ree gen . erlc vlag . ra\r\ncover the shipping , and we ' ll send youour product at no cost to prove its\r\neffectiveness .\r\nwon ' t last . . . hurry\r\nstop promos .\r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3
Subject: we ' ve found a school for you !\r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
Subject: you can be smart !\r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
Subject: fw : crosstex energy , driscoll ranch # 1 , # 3 , meter nos . 9858 and\r\n9868\r\nplease note the following for april production regarding the crosstex\r\ncontract : 96048744 at the above referenced location .\r\nthank you ,\r\nmelissa\r\n- - - - - original message - - - - -\r\nfrom : bubert , jerry\r\nsent : thursday , march 22 , 2001 2 : 19 pm\r\nto : taylor , vance l .\r\ncc : flynn , shawna ; graves , melissa ; harris , joanne ; reinhardt , donald p . ;\r\nriley , brian ; smith , susan ; sweeney , christy ; walker , robert ; weissman , george\r\nsubject : crosstex energy , driscoll ranch # 1 , # 3 , meter nos . 9858 and 9868\r\nper section 2 . 2 of the gpa , crosstex has elected to sell 4000 mmbtu / d in the\r\naggragate at the base contract price of if hsc less $ 0 . 10 , and the excess of\r\nthe available gas over 4000 mmbtu / d in the aggragate at gda hsc less $ 0 . 15 .                                                                                                                                                                                                                                                                    1
Subject: put the 10 on the ft\r\nthe transport volumes decreased from 25000 to 10000 . all 10000 should be on\r\ncontract 012 - 41991 - 203 .\r\nthanks ,\r\nami\r\n- - - - - - - - - - - - - - - - - - - - - - forwarded by ami chokshi / corp / enron on 08 / 31 / 2000\r\n10 : 54 am - - - - - - - - - - - - - - - - - - - - - - - - - - -\r\nroyal _ b _ edmondson @ reliantenergy . com on 08 / 31 / 2000 10 : 47 : 37 am\r\nto : ami _ chokshi @ enron . com\r\ncc :\r\nsubject : put the 10 on the ft\r\n( see attached file : hpl - sept . xls )\r\n- hpl - sept . xls                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Subject: 3 / 4 / 2000 and following noms\r\nhpl can ' t take the extra 15 mmcf / d over the weekend . we ' ll try next week ,\r\nbut for now the nom will stay at 60 mmcf / d , with redeliveries as they have\r\nbeen\r\n-\r\n50 into pg & e , 7 from fcv , and 3 at carthage .\r\n- - - - - - - - - - - - - - - - - - - - - - forwarded by bruce mcmills / ftworth / pefs / pec on\r\n03 / 03 / 2000\r\n09 : 42 am - - - - - - - - - - - - - - - - - - - - - - - - - - -\r\nbruce mcmills\r\n03 / 03 / 2000 09 : 10 am\r\nto : dfarmer @ enron . com , briley @ enron . com , stacey . neuweiler @ enron . com\r\ncc : chad w . cass / gcs / cec / pec @ pec , william e . speckels / gcs / cec / pec @ pec , donna\r\nc . spencer / gcs / cec / pec @ pec , michael r . cherry / easttexas / pefs / pec @ pec ,\r\ndarrel f . bane / easttexas / pefs / pec @ pec\r\nsubject : 3 / 4 / 2000 and following noms\r\nthis is to nominate 75 , 000 mmbtu / d into eastrans for 3 / 4 / 2000 and following .\r\nwe will deliver 50 , 000 into pg & e , 7 , 000 from fuel cotton valley ( continue\r\n750\r\nmmbtu / d sale ) ,\r\nand 18 , 000 mmbtu / d into your cartwheel agreement at carthage .     1
Subject: industrial worksheets for august 2000 activity\r\nattached are the worksheets for august 2000 activity . there are three\r\ndifferent worksheets { 2 - supply & 1 - market } .\r\nthe market worksheet is preliminary and will continuously be updated\r\nthroughout the month .\r\nthe supply worksheets capture all " buybacks and the relevant pricing data .\r\nthese three worksheets can be found in two separate files . o :\r\nlogistics / robert lloyd / buydeaug 2000 . xls . . . . . . . . . . . . . supply\r\no : logistics / ken\r\nsorry for the delay in providing you ' ll this data .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Subject: important online banking alert\r\ndear valued citizensr bank member ,\r\ndue to concerns , for the safety and integrity of the online banking community we have issued the following warning message .\r\nit has come to our attention that your citizensr bank account information needs to be updated as part of our continuing commitment to protect your account and to reduce the instance of fraud on our website . if you could please take 5 - 10 minutes out of your online experience and renew your records you will not run into any future problems with the online service . however , failure to confirm your records may result in your account suspension .\r\nonce you have confirmed your account records your internet banking service will not be interrupted and will continue as normal .\r\nto confirm your bank account records please click here .\r\nnote :\r\nthis e - mail was sent on behalf of the online banking community , if you do not have an online banking account with charterr one then this message does not apply to you and you may ignore this message .\r\nthank you for your time ,\r\ncitizensr financial group .\r\n                         1
Name: count, Length: 4993, dtype: int64

In [9]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='str')

In [10]:
df.dropna()
df.drop("Unnamed: 0", axis=1)

     label                                               text  label_num
0      ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3     spam  Subject: photoshop , windows , office . cheap ...          1
4      ham  Subject: re : indian springs\r\nthis deal is t...          0
...    ...                                                ...        ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...          0
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...          0
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...          0
5169   ham  Subject: industrial worksheets for august 2000...          0
5170  spam  Subject: important online banking alert\r\ndea...          1

[5171 rows x 3 columns]

In [13]:
df["label_num"].value_counts(normalize=True)*100

label_num
0    71.01141
1    28.98859
Name: proportion, dtype: float64

In [1]:
for i in range(len(df)):
    text = df.values[i][2]
    print(text, "\n")

In [20]:
print(df)

      Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3           4685  spam  Subject: photoshop , windows , office . cheap ...
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...
...          ...   ...                                                ...
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...
5169        1409   ham  Subject: industrial worksheets for august 2000...
5170        4807  spam  Subject: important online banking alert\r\ndea...

      label_num
0             0
1             0
2             0
3             1
4             0
...         ...
5166          0
5167          0
5168          0
5169          0
5170          1

[5171 rows x 4 columns]